services:
  todoapi:
    image: marikatz/todoapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=tcp:marinatodosql123.database.windows.net,1433;Initial Catalog=TodoDb;Persist Security Info=False;User ID=sqladmin;Password=YourStrongP@ssword123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;

  