name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # or 'master' if that’s your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Log in to Azure using publish profile
      uses: azure/webapps-deploy@v2
      with:
        app-name: marinak-todoapi-web
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: marikatz/todoapi:latest
